# Generated by Django 4.1.4 on 2022-12-07 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_matricula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matricula',
            old_name='alunos',
            new_name='aluno',
        ),
        migrations.RenameField(
            model_name='matricula',
            old_name='cursos',
            new_name='curso',
        ),
    ]
